# Generated by Django 5.1.1 on 2025-02-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('pizza', 'Пицца'), ('burger', 'Бургер'), ('salat', 'Salat')], max_length=25),
        ),
        migrations.RemoveField(
            model_name='review',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
